/**
 * Add your action types here.
 * @module constants/ActionTypes
 * @example
 * export const UPDATE_CONTENT = 'UPDATE_CONTENT';
 */

export const NEWSLETTER_SUBSCRIBE = 'NEWSLETTER_SUBSCRIBE';
export const NEWSLETTER_UNSUBSCRIBE = 'NEWSLETTER_UNSUBSCRIBE';
export const NEWSLETTER_CONFIRM_SUBSCRIPTION = 'NEWSLETTER_CONFIRM_SUBSCRIPTION';
export const NEWSLETTER_MESSAGE_SEND = 'NEWSLETTER_MESSAGE_SEND';
export const NEWSLETTER_MESSAGE_SEND_TOGGLE_MODAL = 'NEWSLETTER_MESSAGE_SEND_TOGGLE_MODAL';
export const NEWSLETTER_MESSAGE_TEST_SEND = 'NEWSLETTER_MESSAGE_TEST_SEND';
export const NEWSLETTER_MESSAGE_TEST_SEND_TOGGLE_MODAL = 'NEWSLETTER_MESSAGE_TEST_SEND_TOGGLE_MODAL';
